# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1azA2GQ9PbJTAFlEuOPHmS8AVPYIJfKbj
"""

import os
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
from flask import Flask, render_template, request

# =========================
# Flask設定
# =========================
app = Flask(__name__)
UPLOAD_FOLDER = "static/uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =========================
# モデル読み込み
# =========================
checkpoint = torch.load("cat_dog_model.pth", map_location=DEVICE)
class_names = checkpoint["class_names"]

model = models.efficientnet_b0(pretrained=False)
model.classifier[1] = nn.Linear(
    model.classifier[1].in_features, len(class_names)
)
model.load_state_dict(checkpoint["model_state"])
model.to(DEVICE)
model.eval()

# =========================
# 前処理（学習時と完全一致）
# =========================
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# =========================
# ルーティング
# =========================
@app.route("/", methods=["GET", "POST"])
def index():
    pred_class = None
    image_path = None

    if request.method == "POST":
        file = request.files["image"]
        if file:
            image_path = os.path.join(UPLOAD_FOLDER, file.filename)
            file.save(image_path)

            img = Image.open(image_path).convert("RGB")
            img = transform(img).unsqueeze(0).to(DEVICE)

            with torch.no_grad():
                outputs = model(img)
                pred_idx = outputs.argmax(dim=1).item()
                pred_class = class_names[pred_idx]

    return render_template(
        "index.html",
        pred_class=pred_class,
        image_path=image_path
    )

if __name__ == "__main__":
    app.run(debug=True)